/**
 * Product data for Mietpark WW.
 *
 * These functions mimic the Supabase API so switching to real data
 * later is a one-line change per call site:
 *   getProducts() → supabase.from("products").select("*")
 *
 * Categorization:
 *   maschine  – Motorgetriebene Geräte, schwere Baumaschinen
 *   werkzeug  – Handgeräte, Messinstrumente, Klemmen, Zangen
 *   zubehoer  – Gerüste, Container, Infrastruktur, Baustrom
 */

import type { Product } from "@/types/database";

export const PRODUCTS: Product[] = [
  // ═══════════════════════════════════════════════════════════
  // MASCHINEN
  // ═══════════════════════════════════════════════════════════

  {
    id: "mp-001",
    created_at: "2026-02-21",
    updated_at: "2026-02-21",
    name: "Minibagger 3,5 Tonnen",
    slug: "minibagger-3-5t",
    description:
      "Leistungsstarker Minibagger mit 3,5 Tonnen Einsatzgewicht. Vielseitig einsetzbar für Erdarbeiten, Aushub, Kanalbau und Abbrucharbeiten. Nullheck-Design ermöglicht Arbeiten auf engem Raum. Inklusive Standardlöffel.",
    category: "maschine",
    images: [],
    serial_number: null,
    manufacturer: null,
    model: "3,5t",
    year: null,
    weight_kg: 3500,
    specs: {
      Einsatzgewicht: "3.500 kg",
      Grabtiefe: "ca. 3,2 m",
      Bauart: "Nullheck",
    },
    price_daily: 16200,
    price_weekend: 14600,
    price_weekly: 12900,
    price_monthly: 8100,
    deposit_amount: 50000,
    questionnaire_type: "ausfuehrlich",
    status: "verfuegbar",
    qr_code_id: "MP-001",
    last_maintenance: null,
    next_maintenance: null,
    maintenance_notes: null,
  },
  {
    id: "mp-002",
    created_at: "2026-02-21",
    updated_at: "2026-02-21",
    name: "Holzspalter am Anhänger",
    slug: "holzspalter-anhaenger",
    description:
      "Mobiler Holzspalter auf Straßenanhänger mit 22 Tonnen Spaltkraft. Kann direkt an den Einsatzort gefahren werden (Führerschein BE erforderlich). Geeignet für Stammholz bis 60 cm Durchmesser.",
    category: "maschine",
    images: [],
    serial_number: null,
    manufacturer: "Posch",
    model: "22t Anhänger",
    year: null,
    weight_kg: null,
    specs: {
      Spaltkraft: "22 Tonnen",
      "Max. Spalthöhe": "60 cm",
      Transport: "Straßenanhänger (BE-Führerschein)",
    },
    price_daily: 6700,
    price_weekend: 6300,
    price_weekly: 5400,
    price_monthly: 4200,
    deposit_amount: 15000,
    questionnaire_type: "kurz",
    status: "verfuegbar",
    qr_code_id: "MP-002",
    last_maintenance: null,
    next_maintenance: null,
    maintenance_notes: null,
  },
  {
    id: "mp-003",
    created_at: "2026-02-21",
    updated_at: "2026-02-21",
    name: "Asthäcksler Dreipunkt",
    slug: "asthaecksler-dreipunkt",
    description:
      "Leistungsstarker Asthäcksler mit Dreipunktanbau für den Traktor. Ideal für Grünschnitt, Baumschnitt und Gartenabfälle. Zerkleinert Äste schnell und effizient zu verwertbarem Häckselgut.",
    category: "maschine",
    images: [],
    serial_number: null,
    manufacturer: null,
    model: "Dreipunkt",
    year: null,
    weight_kg: null,
    specs: {
      Anbau: "Dreipunktaufhängung",
      Einsatz: "Grünschnitt, Baumschnitt",
    },
    price_daily: 19700,
    price_weekend: 17700,
    price_weekly: 15800,
    price_monthly: 9800,
    deposit_amount: 30000,
    questionnaire_type: "ausfuehrlich",
    status: "verfuegbar",
    qr_code_id: "MP-003",
    last_maintenance: null,
    next_maintenance: null,
    maintenance_notes: null,
  },
  {
    id: "mp-004",
    created_at: "2026-02-21",
    updated_at: "2026-02-21",
    name: "Rüttelplatte Weber WHV 6013",
    slug: "ruettelplatte-weber-whv-6013",
    description:
      "Schwere Rüttelplatte mit 600 kg Betriebsgewicht. Geeignet für den Straßen- und Wegebau, Pflasterarbeiten und großflächige Verdichtungsaufgaben. Zuverlässige Verdichtungsleistung für anspruchsvolle Projekte.",
    category: "maschine",
    images: [],
    serial_number: null,
    manufacturer: "Weber",
    model: "WHV 6013",
    year: null,
    weight_kg: 600,
    specs: {
      Betriebsgewicht: "600 kg",
      Hersteller: "Weber",
      Modell: "WHV 6013",
    },
    price_daily: 6700,
    price_weekend: 6600,
    price_weekly: 5400,
    price_monthly: 3600,
    deposit_amount: 15000,
    questionnaire_type: "kurz",
    status: "verfuegbar",
    qr_code_id: "MP-004",
    last_maintenance: null,
    next_maintenance: null,
    maintenance_notes: null,
  },
  {
    id: "mp-005",
    created_at: "2026-02-21",
    updated_at: "2026-02-21",
    name: "Nassschneidemaschine SSB EGO400",
    slug: "nassschneidemaschine-ssb-ego400",
    description:
      "Nassschneidemaschine mit 2,2 kW Leistung für präzise Schnitte in Fliesen, Naturstein und Betonplatten. Wassergekühltes Diamantblatt für staubfreies Arbeiten und saubere Schnittkanten.",
    category: "maschine",
    images: [],
    serial_number: null,
    manufacturer: "SSB",
    model: "EGO400",
    year: null,
    weight_kg: null,
    specs: {
      Leistung: "2,2 kW",
      Blattdurchmesser: "400 mm",
      Kühlung: "Wassergekühlt",
    },
    price_daily: 3000,
    price_weekend: 2700,
    price_weekly: 2500,
    price_monthly: 2100,
    deposit_amount: 10000,
    questionnaire_type: "kurz",
    status: "verfuegbar",
    qr_code_id: "MP-005",
    last_maintenance: null,
    next_maintenance: null,
    maintenance_notes: null,
  },
  {
    id: "mp-006",
    created_at: "2026-02-17",
    updated_at: "2026-02-17",
    name: "Baukreissäge Atika ATU 450",
    slug: "baukreissaege-atika-atu-450",
    description:
      "Robuste Baukreissäge mit 450 mm Sägeblatt. Ideal für den Zuschnitt von Bauholz, Schalungsbrettern und Dachlatten direkt auf der Baustelle. Stabile Bauweise für den täglichen Einsatz.",
    category: "maschine",
    images: [],
    serial_number: null,
    manufacturer: "Atika",
    model: "ATU 450",
    year: null,
    weight_kg: null,
    specs: {
      Sägeblatt: "Ø 450 mm",
      Hersteller: "Atika",
      Modell: "ATU 450",
    },
    price_daily: 2800,
    price_weekend: 2500,
    price_weekly: 2200,
    price_monthly: 1800,
    deposit_amount: 10000,
    questionnaire_type: "kurz",
    status: "verfuegbar",
    qr_code_id: "MP-006",
    last_maintenance: null,
    next_maintenance: null,
    maintenance_notes: null,
  },
  {
    id: "mp-007",
    created_at: "2026-02-17",
    updated_at: "2026-02-17",
    name: "Dämmstoffsäge",
    slug: "daemmstoffsaege",
    description:
      "Elektrische Dämmstoffsäge für den sauberen und effizienten Zuschnitt von Dämmmaterialien. Ermöglicht gerade Schnitte in Mineralwolle, Styropor und anderen Dämmstoffen ohne Ausfransen.",
    category: "maschine",
    images: [],
    serial_number: null,
    manufacturer: null,
    model: null,
    year: null,
    weight_kg: null,
    specs: {
      Einsatz: "Mineralwolle, Styropor, Dämmstoffe",
    },
    price_daily: 3000,
    price_weekend: 2500,
    price_weekly: 1800,
    price_monthly: 1500,
    deposit_amount: 5000,
    questionnaire_type: "kurz",
    status: "verfuegbar",
    qr_code_id: "MP-007",
    last_maintenance: null,
    next_maintenance: null,
    maintenance_notes: null,
  },
  {
    id: "mp-008",
    created_at: "2026-02-17",
    updated_at: "2026-02-17",
    name: "Betonmischer",
    slug: "betonmischer",
    description:
      "Zuverlässiger Betonmischer für die Baustelle. Mischt Beton, Mörtel und Estrich gleichmäßig und effizient. Robust gebaut für den täglichen Einsatz im Hoch- und Tiefbau.",
    category: "maschine",
    images: [],
    serial_number: null,
    manufacturer: null,
    model: null,
    year: null,
    weight_kg: null,
    specs: {
      Einsatz: "Beton, Mörtel, Estrich",
    },
    price_daily: 1800,
    price_weekend: 1600,
    price_weekly: 1500,
    price_monthly: 900,
    deposit_amount: 5000,
    questionnaire_type: "kurz",
    status: "verfuegbar",
    qr_code_id: "MP-008",
    last_maintenance: null,
    next_maintenance: null,
    maintenance_notes: null,
  },
  {
    id: "mp-009",
    created_at: "2026-02-17",
    updated_at: "2026-02-17",
    name: "Betonrührgerät",
    slug: "betonruehrgeraet",
    description:
      "Kraftvolles Rührgerät zum Anmischen von Beton, Fliesenkleber, Putzen und diversen anderen Baumaterialien. Spart Zeit und Kraft gegenüber dem Mischen von Hand.",
    category: "maschine",
    images: [],
    serial_number: null,
    manufacturer: null,
    model: null,
    year: null,
    weight_kg: null,
    specs: {
      Einsatz: "Beton, Fliesenkleber, Putze, Baumaterialien",
    },
    price_daily: 2700,
    price_weekend: 2400,
    price_weekly: 2200,
    price_monthly: 1400,
    deposit_amount: 5000,
    questionnaire_type: "kurz",
    status: "verfuegbar",
    qr_code_id: "MP-009",
    last_maintenance: null,
    next_maintenance: null,
    maintenance_notes: null,
  },
  {
    id: "mp-010",
    created_at: "2026-02-17",
    updated_at: "2026-02-17",
    name: "Abbruchhammer Bosch",
    slug: "abbruchhammer-bosch",
    description:
      "Elektrischer Abbruchhammer von Bosch für Stemm- und Abbrucharbeiten. Durchbricht Beton, Mauerwerk und Fliesen mit hoher Schlagkraft. Ideal für Renovierungen und Rückbau.",
    category: "maschine",
    images: [],
    serial_number: null,
    manufacturer: "Bosch",
    model: null,
    year: null,
    weight_kg: null,
    specs: {
      Hersteller: "Bosch",
      Einsatz: "Stemm- und Abbrucharbeiten",
    },
    price_daily: 2200,
    price_weekend: 2000,
    price_weekly: 1800,
    price_monthly: 1500,
    deposit_amount: 10000,
    questionnaire_type: "kurz",
    status: "verfuegbar",
    qr_code_id: "MP-010",
    last_maintenance: null,
    next_maintenance: null,
    maintenance_notes: null,
  },
  {
    id: "mp-011",
    created_at: "2026-02-17",
    updated_at: "2026-02-17",
    name: "Mauernutfräse",
    slug: "mauernutfraese",
    description:
      "Mauernutfräse zum sauberen Fräsen von Schlitzen in Mauerwerk und Beton. Für die Verlegung von Elektroleitungen, Wasserleitungen und Heizungsrohren. Staubarmes Arbeiten mit Absaugvorrichtung.",
    category: "maschine",
    images: [],
    serial_number: null,
    manufacturer: null,
    model: null,
    year: null,
    weight_kg: null,
    specs: {
      Einsatz: "Schlitze in Mauerwerk und Beton",
    },
    price_daily: 3600,
    price_weekend: 3300,
    price_weekly: 2800,
    price_monthly: 1800,
    deposit_amount: 10000,
    questionnaire_type: "kurz",
    status: "verfuegbar",
    qr_code_id: "MP-011",
    last_maintenance: null,
    next_maintenance: null,
    maintenance_notes: null,
  },
  {
    id: "mp-012",
    created_at: "2026-02-17",
    updated_at: "2026-02-17",
    name: "Bautrockner",
    slug: "bautrockner",
    description:
      "Professionelles Trocknungsgerät zur Bautrocknung. Entzieht Feuchtigkeit aus Neubauten, nach Wasserschäden oder bei Renovierungen. Beschleunigt den Trocknungsprozess erheblich.",
    category: "maschine",
    images: [],
    serial_number: null,
    manufacturer: null,
    model: null,
    year: null,
    weight_kg: null,
    specs: {
      Einsatz: "Bautrocknung, Wasserschadenbeseitigung",
    },
    price_daily: 2000,
    price_weekend: 1800,
    price_weekly: 1650,
    price_monthly: 1500,
    deposit_amount: 5000,
    questionnaire_type: "kurz",
    status: "verfuegbar",
    qr_code_id: "MP-012",
    last_maintenance: null,
    next_maintenance: null,
    maintenance_notes: null,
  },
  {
    id: "mp-013",
    created_at: "2026-02-17",
    updated_at: "2026-02-17",
    name: "Propan-Schweißgerät ICOPal",
    slug: "propan-schweissgeraet-icopal",
    description:
      "Propan-Schweißgerät für die Verarbeitung von Dachfolien und Bitumenbahnen. Gleichmäßige Flamme für sichere und professionelle Verschweißungen. Propan-Gasflasche gegen Kaution verfügbar.",
    category: "maschine",
    images: [],
    serial_number: null,
    manufacturer: "ICOPal",
    model: "455001",
    year: null,
    weight_kg: null,
    specs: {
      Hersteller: "ICOPal",
      Modell: "455001",
      Einsatz: "Dachfolien, Bitumenbahnen",
      Hinweis: "Propan-Gasflasche gegen Kaution verfügbar",
    },
    price_daily: 2500,
    price_weekend: 2200,
    price_weekly: 2000,
    price_monthly: 1500,
    deposit_amount: 5000,
    questionnaire_type: "kurz",
    status: "verfuegbar",
    qr_code_id: "MP-013",
    last_maintenance: null,
    next_maintenance: null,
    maintenance_notes: null,
  },

  // ═══════════════════════════════════════════════════════════
  // WERKZEUGE
  // ═══════════════════════════════════════════════════════════

  {
    id: "mp-014",
    created_at: "2026-02-17",
    updated_at: "2026-02-17",
    name: "Rotationslaser",
    slug: "rotationslaser",
    description:
      "Präziser Rotationslaser für Nivellierarbeiten. Selbstnivellierend mit hoher Reichweite. Ideal für Fundament-, Estrich- und Tiefbauarbeiten. Inklusive Empfänger und Stativ.",
    category: "werkzeug",
    images: [],
    serial_number: null,
    manufacturer: null,
    model: null,
    year: null,
    weight_kg: null,
    specs: {
      Einsatz: "Fundament, Estrich, Tiefbau",
      Lieferumfang: "Laser, Empfänger, Stativ",
    },
    price_daily: 3600,
    price_weekend: 3200,
    price_weekly: 2900,
    price_monthly: 1800,
    deposit_amount: 10000,
    questionnaire_type: "kurz",
    status: "verfuegbar",
    qr_code_id: "MP-014",
    last_maintenance: null,
    next_maintenance: null,
    maintenance_notes: null,
  },
  {
    id: "mp-015",
    created_at: "2026-02-17",
    updated_at: "2026-02-17",
    name: "Nivelliergerät",
    slug: "nivelliergeraet",
    description:
      "Optisches Nivelliergerät für präzise Höhenmessungen auf der Baustelle. Unverzichtbar für Fundamentarbeiten, Pflasterarbeiten und Geländeaufnahmen.",
    category: "werkzeug",
    images: [],
    serial_number: null,
    manufacturer: null,
    model: null,
    year: null,
    weight_kg: null,
    specs: {
      Einsatz: "Höhenmessungen, Fundamentarbeiten",
    },
    price_daily: 1500,
    price_weekend: 1400,
    price_weekly: 1300,
    price_monthly: 1100,
    deposit_amount: 5000,
    questionnaire_type: "kurz",
    status: "verfuegbar",
    qr_code_id: "MP-015",
    last_maintenance: null,
    next_maintenance: null,
    maintenance_notes: null,
  },
  {
    id: "mp-016",
    created_at: "2026-02-17",
    updated_at: "2026-02-17",
    name: "Versetzzange 40 cm",
    slug: "versetzzange-40cm",
    description:
      "Versetzzange für Stufen- und Winkelsteine bis 40 cm Breite. Ermöglicht sicheres und rückenschonendes Versetzen schwerer Betonsteine mit dem Bagger oder Kran.",
    category: "werkzeug",
    images: [],
    serial_number: null,
    manufacturer: null,
    model: "40 cm",
    year: null,
    weight_kg: null,
    specs: {
      Greifbreite: "bis 40 cm",
      Einsatz: "Stufen, Winkelsteine, Bordsteine",
    },
    price_daily: 4500,
    price_weekend: 4000,
    price_weekly: 3600,
    price_monthly: 2100,
    deposit_amount: 10000,
    questionnaire_type: "kurz",
    status: "verfuegbar",
    qr_code_id: "MP-016",
    last_maintenance: null,
    next_maintenance: null,
    maintenance_notes: null,
  },
  {
    id: "mp-017",
    created_at: "2026-02-17",
    updated_at: "2026-02-17",
    name: "Versetzzange 20 cm",
    slug: "versetzzange-20cm",
    description:
      "Kompakte Versetzzange für kleinere Betonsteine bis 20 cm Breite. Für präzises Versetzen von Pflastersteinen, L-Steinen und ähnlichen Elementen.",
    category: "werkzeug",
    images: [],
    serial_number: null,
    manufacturer: null,
    model: "20 cm",
    year: null,
    weight_kg: null,
    specs: {
      Greifbreite: "bis 20 cm",
      Einsatz: "Pflastersteine, L-Steine",
    },
    price_daily: 4500,
    price_weekend: 2800,
    price_weekly: 1900,
    price_monthly: 1500,
    deposit_amount: 10000,
    questionnaire_type: "kurz",
    status: "verfuegbar",
    qr_code_id: "MP-017",
    last_maintenance: null,
    next_maintenance: null,
    maintenance_notes: null,
  },
  {
    id: "mp-018",
    created_at: "2026-02-17",
    updated_at: "2026-02-17",
    name: "Blockklemmen",
    slug: "blockklemmen",
    description:
      "Blockklemmen zum sicheren Greifen und Versetzen von Betonblöcken, Mauersteinen und Bordsteinen. Erleichtert das Handling schwerer Baumaterialien erheblich.",
    category: "werkzeug",
    images: [],
    serial_number: null,
    manufacturer: null,
    model: null,
    year: null,
    weight_kg: null,
    specs: {
      Einsatz: "Betonblöcke, Mauersteine, Bordsteine",
    },
    price_daily: 2600,
    price_weekend: 2600,
    price_weekly: 1700,
    price_monthly: 1300,
    deposit_amount: 5000,
    questionnaire_type: "kurz",
    status: "verfuegbar",
    qr_code_id: "MP-018",
    last_maintenance: null,
    next_maintenance: null,
    maintenance_notes: null,
  },
  {
    id: "mp-019",
    created_at: "2026-02-17",
    updated_at: "2026-02-17",
    name: "Rinneisenbiegegerät",
    slug: "rinneisenbiegegeraet",
    description:
      "Rinneisenbiegegerät zum präzisen Biegen von Rinneisen und Bewehrungsstahl. Unverzichtbar für Betonarbeiten und Armierungsarbeiten auf der Baustelle.",
    category: "werkzeug",
    images: [],
    serial_number: null,
    manufacturer: null,
    model: null,
    year: null,
    weight_kg: null,
    specs: {
      Einsatz: "Rinneisen, Bewehrungsstahl",
    },
    price_daily: 800,
    price_weekend: 700,
    price_weekly: 600,
    price_monthly: 500,
    deposit_amount: 2000,
    questionnaire_type: "kurz",
    status: "verfuegbar",
    qr_code_id: "MP-019",
    last_maintenance: null,
    next_maintenance: null,
    maintenance_notes: null,
  },
  {
    id: "mp-020",
    created_at: "2026-02-21",
    updated_at: "2026-02-21",
    name: "Schalungsklemmen-Set",
    slug: "schalungsklemmen-set",
    description:
      "Set aus Schalungsklemmen für Sturz- und Mauerschalung. Ermöglicht schnelles und sicheres Einschalen von Stürzen, Ringanker und Mauerwerksöffnungen.",
    category: "werkzeug",
    images: [],
    serial_number: null,
    manufacturer: null,
    model: null,
    year: null,
    weight_kg: null,
    specs: {
      Einsatz: "Sturzschalung, Mauerschalung, Ringanker",
    },
    price_daily: 400,
    price_weekend: 400,
    price_weekly: 300,
    price_monthly: 200,
    deposit_amount: 2000,
    questionnaire_type: "kurz",
    status: "verfuegbar",
    qr_code_id: "MP-020",
    last_maintenance: null,
    next_maintenance: null,
    maintenance_notes: null,
  },

  // ═══════════════════════════════════════════════════════════
  // ZUBEHÖR & INFRASTRUKTUR
  // ═══════════════════════════════════════════════════════════

  {
    id: "mp-021",
    created_at: "2026-02-17",
    updated_at: "2026-02-17",
    name: "Rollgerüst 5 m",
    slug: "rollgeruest-5m",
    description:
      "Mobiles Rollgerüst mit 5 m Arbeitshöhe. Schnell aufgebaut und flexibel versetzbar. Ideal für Fassadenarbeiten, Malerarbeiten und Installationsarbeiten in der Höhe.",
    category: "zubehoer",
    images: [],
    serial_number: null,
    manufacturer: null,
    model: "5 m",
    year: null,
    weight_kg: null,
    specs: {
      Arbeitshöhe: "5 m",
      Bauart: "Rollgerüst, mobil",
    },
    price_daily: 4200,
    price_weekend: 4000,
    price_weekly: 3600,
    price_monthly: 2200,
    deposit_amount: 15000,
    questionnaire_type: "kurz",
    status: "verfuegbar",
    qr_code_id: "MP-021",
    last_maintenance: null,
    next_maintenance: null,
    maintenance_notes: null,
  },
  {
    id: "mp-022",
    created_at: "2026-02-17",
    updated_at: "2026-02-17",
    name: "Fassadengerüst Plettac",
    slug: "fassadengeruest-plettac",
    description:
      "Stahlrohrgerüst System Plettac, 70 cm Breite. Inklusive Streben, Füße und Zubehör. Preis pro Quadratmeter für 4 Wochen. Ideal für Fassadenarbeiten, Dacharbeiten und größere Renovierungsprojekte.",
    category: "zubehoer",
    images: [],
    serial_number: null,
    manufacturer: "Plettac",
    model: "70 cm Breite",
    year: null,
    weight_kg: null,
    specs: {
      System: "Plettac Stahlrohr",
      Breite: "70 cm",
      Lieferumfang: "Gerüst, Streben, Füße, Zubehör",
      Hinweis: "Preis pro m² für 4 Wochen",
    },
    price_daily: 500,
    price_weekend: 500,
    price_weekly: 500,
    price_monthly: 500,
    deposit_amount: 20000,
    questionnaire_type: "ausfuehrlich",
    status: "verfuegbar",
    qr_code_id: "MP-022",
    last_maintenance: null,
    next_maintenance: null,
    maintenance_notes: null,
  },
  {
    id: "mp-023",
    created_at: "2026-02-21",
    updated_at: "2026-02-21",
    name: "Materialcontainer 4 × 2 m",
    slug: "materialcontainer-4x2m",
    description:
      "Abschließbarer Materialcontainer mit 4 × 2 m Grundfläche. Sicherer Lagerort für Werkzeuge, Baumaterialien und Geräte auf der Baustelle. Wetterfest und einbruchsicher.",
    category: "zubehoer",
    images: [],
    serial_number: null,
    manufacturer: null,
    model: "4 × 2 m",
    year: null,
    weight_kg: null,
    specs: {
      Grundfläche: "4,00 × 2,00 m",
      Bauart: "Abschließbar, wetterfest",
    },
    price_daily: 2000,
    price_weekend: 2000,
    price_weekly: 2000,
    price_monthly: 1800,
    deposit_amount: 20000,
    questionnaire_type: "kurz",
    status: "verfuegbar",
    qr_code_id: "MP-023",
    last_maintenance: null,
    next_maintenance: null,
    maintenance_notes: null,
  },
  {
    id: "mp-024",
    created_at: "2026-02-21",
    updated_at: "2026-02-21",
    name: "Bauaufzug 8 m",
    slug: "bauaufzug-8m",
    description:
      "Bauaufzug mit 8 m Förderhöhe und 400 kg Tragkraft. Transportiert Material sicher und effizient auf höher gelegene Stockwerke. Spart Zeit und körperliche Belastung beim Materialtransport.",
    category: "zubehoer",
    images: [],
    serial_number: null,
    manufacturer: null,
    model: "8 m / 400 kg",
    year: null,
    weight_kg: null,
    specs: {
      Förderhöhe: "8 m",
      Tragkraft: "400 kg",
    },
    price_daily: 8400,
    price_weekend: 8400,
    price_weekly: 7000,
    price_monthly: 5000,
    deposit_amount: 20000,
    questionnaire_type: "ausfuehrlich",
    status: "verfuegbar",
    qr_code_id: "MP-024",
    last_maintenance: null,
    next_maintenance: null,
    maintenance_notes: null,
  },
  {
    id: "mp-025",
    created_at: "2026-02-17",
    updated_at: "2026-02-17",
    name: "Baustromkasten",
    slug: "baustromkasten",
    description:
      "Geprüfter Baustromkasten für die sichere Stromversorgung auf der Baustelle. Mit FI-Schutzschalter und verschiedenen Steckdosen für alle gängigen Baustromverbraucher.",
    category: "zubehoer",
    images: [],
    serial_number: null,
    manufacturer: null,
    model: null,
    year: null,
    weight_kg: null,
    specs: {
      Schutz: "FI-Schutzschalter",
      Einsatz: "Baustromversorgung",
    },
    price_daily: 1300,
    price_weekend: 1300,
    price_weekly: 1300,
    price_monthly: 1100,
    deposit_amount: 5000,
    questionnaire_type: "kurz",
    status: "verfuegbar",
    qr_code_id: "MP-025",
    last_maintenance: null,
    next_maintenance: null,
    maintenance_notes: null,
  },
];

// ─── DATA ACCESS FUNCTIONS ──────────────────────────────────
// Replace these with Supabase queries when ready.

export function getProducts(): Product[] {
  return PRODUCTS;
}

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getProductsByCategory(category: string): Product[] {
  if (category === "alle") return PRODUCTS;
  return PRODUCTS.filter((p) => p.category === category);
}

export function getAvailableProducts(): Product[] {
  return PRODUCTS.filter((p) => p.status === "verfuegbar");
}
